-- Лабораторная работа 5. Вариант 11. БД «Автомастерская».
-- Студент: Харьковский Семён, группа К3341.

\set ON_ERROR_STOP on
\pset pager off
\echo 'ЛР5. Подключение к базе autoservice_v11'

SET search_path TO autoservice, public;

-- =====================================================================
-- 0. СЛУЖЕБНЫЕ ОБЪЕКТЫ ДЛЯ ПРОЦЕДУР И ТРИГГЕРОВ
-- =====================================================================

-- Совместимость деталей с марками автомобилей позволяет однозначно
-- определить детали для Ford независимо от истории выполненных заказов.
CREATE TABLE IF NOT EXISTS part_brand_compatibility (
    compatibility_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id           INTEGER NOT NULL,
    brand_id          INTEGER NOT NULL,
    CONSTRAINT fk_part_compatibility_part FOREIGN KEY (part_id)
        REFERENCES parts (part_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_part_compatibility_brand FOREIGN KEY (brand_id)
        REFERENCES car_brands (brand_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_part_brand_compatibility UNIQUE (part_id, brand_id)
);

INSERT INTO car_brands (brand_id, brand_name, country)
VALUES (11, 'Ford', 'США')
ON CONFLICT (brand_name) DO UPDATE SET country = EXCLUDED.country;

INSERT INTO part_brand_compatibility (part_id, brand_id)
SELECT p.part_id, b.brand_id
FROM parts p
CROSS JOIN car_brands b
WHERE p.part_id IN (1, 4) AND b.brand_name = 'Ford'
ON CONFLICT (part_id, brand_id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('car_brands', 'brand_id'),
    (SELECT MAX(brand_id) FROM car_brands)
);

-- Таблица аудита истории цен.
CREATE TABLE IF NOT EXISTS work_price_audit (
    audit_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_price_id   INTEGER,
    work_type_id    INTEGER,
    operation       VARCHAR(10) NOT NULL,
    old_labor_price NUMERIC(12,2),
    new_labor_price NUMERIC(12,2),
    old_valid_from  DATE,
    old_valid_to    DATE,
    new_valid_from  DATE,
    new_valid_to    DATE,
    changed_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by      TEXT NOT NULL DEFAULT CURRENT_USER,
    CONSTRAINT ck_work_price_audit_operation
        CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE'))
);

-- =====================================================================
-- 1. ХРАНИМЫЕ ПРОЦЕДУРЫ ВАРИАНТА 11
-- =====================================================================

-- 1.1. Повышение цены деталей для автомобилей Ford на 10%.
-- Параметры позволяют использовать процедуру и для другой марки/процента.
CREATE OR REPLACE PROCEDURE p_increase_part_prices(
    IN p_brand_name TEXT DEFAULT 'Ford',
    IN p_percent NUMERIC DEFAULT 10,
    INOUT p_updated_rows INTEGER DEFAULT 0
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_percent <= 0 OR p_percent > 100 THEN
        RAISE EXCEPTION 'Процент повышения должен быть в диапазоне (0; 100]';
    END IF;

    UPDATE parts p
       SET unit_price = ROUND(p.unit_price * (1 + p_percent / 100.0), 2)
     WHERE EXISTS (
         SELECT 1
           FROM part_brand_compatibility pbc
           JOIN car_brands b ON b.brand_id = pbc.brand_id
          WHERE pbc.part_id = p.part_id
            AND LOWER(b.brand_name) = LOWER(p_brand_name)
     );

    GET DIAGNOSTICS p_updated_rows = ROW_COUNT;
    RAISE NOTICE 'Обновлено цен деталей: %', p_updated_rows;
END;
$$;

-- 1.2. Повышение разряда мастеров, отремонтировавших больше 3 автомобилей.
-- Один завершённый заказ соответствует ремонту одного автомобиля.
CREATE OR REPLACE PROCEDURE p_promote_productive_masters(
    IN p_min_repaired_cars INTEGER DEFAULT 3,
    INOUT p_promoted_rows INTEGER DEFAULT 0
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_min_repaired_cars < 0 THEN
        RAISE EXCEPTION 'Минимальное число ремонтов не может быть отрицательным';
    END IF;

    WITH productive_masters AS (
        SELECT wa.master_id
          FROM work_assignments wa
          JOIN order_services os ON os.order_service_id = wa.order_service_id
          JOIN orders o ON o.order_id = os.order_id
         WHERE o.actual_end_date IS NOT NULL
         GROUP BY wa.master_id
        HAVING COUNT(DISTINCT o.order_id) > p_min_repaired_cars
    )
    UPDATE employees e
       SET grade = LEAST(e.grade + 1, 6)
      FROM productive_masters pm
     WHERE e.employee_id = pm.master_id
       AND e.grade IS NOT NULL
       AND e.grade < 6;

    GET DIAGNOSTICS p_promoted_rows = ROW_COUNT;
    RAISE NOTICE 'Повышен разряд мастеров: %', p_promoted_rows;
END;
$$;

-- 1.3. Число автомобилей, отремонтированных каждым мастером за квартал.
-- Результат возвращается через курсор, что позволяет получить набор строк из CALL.
CREATE OR REPLACE PROCEDURE p_repaired_cars_by_master(
    IN p_quarter_start DATE DEFAULT DATE_TRUNC('quarter', CURRENT_DATE)::DATE,
    INOUT p_result REFCURSOR DEFAULT 'quarter_repair_counts'
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_quarter_start IS NULL THEN
        RAISE EXCEPTION 'Дата начала квартала не задана';
    END IF;

    OPEN p_result FOR
        SELECT e.employee_id,
               e.last_name,
               e.first_name,
               COUNT(DISTINCT o.order_id) AS repaired_car_count
          FROM employees e
          JOIN positions pos ON pos.position_id = e.position_id
          LEFT JOIN work_assignments wa ON wa.master_id = e.employee_id
          LEFT JOIN order_services os ON os.order_service_id = wa.order_service_id
          LEFT JOIN orders o
            ON o.order_id = os.order_id
           AND o.actual_end_date >= p_quarter_start
           AND o.actual_end_date < p_quarter_start + INTERVAL '3 months'
         WHERE pos.position_name = 'мастер'
         GROUP BY e.employee_id, e.last_name, e.first_name
         ORDER BY repaired_car_count DESC, e.last_name, e.first_name;
END;
$$;

-- =====================================================================
-- 2. СЕМЬ ТРИГГЕРОВ ДЛЯ БД «АВТОМАСТЕРСКАЯ»
-- =====================================================================

-- 2.1. Проверка специализации назначаемого мастера.
CREATE OR REPLACE FUNCTION fn_check_master_qualification()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_work_type_id INTEGER;
BEGIN
    SELECT os.work_type_id
      INTO v_work_type_id
      FROM order_services os
     WHERE os.order_service_id = NEW.order_service_id;

    IF EXISTS (
        SELECT 1 FROM work_type_specializations wts
        WHERE wts.work_type_id = v_work_type_id
    ) AND EXISTS (
        SELECT 1
          FROM work_type_specializations wts
         WHERE wts.work_type_id = v_work_type_id
           AND NOT EXISTS (
               SELECT 1
                 FROM employee_specializations es
                WHERE es.employee_id = NEW.master_id
                  AND es.specialization_id = wts.specialization_id
           )
    ) THEN
        RAISE EXCEPTION
            'Мастер % не имеет специализации, требуемой для вида работы %',
            NEW.master_id, v_work_type_id;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_assignment_master_qualification ON work_assignments;
CREATE TRIGGER trg_assignment_master_qualification
BEFORE INSERT OR UPDATE OF master_id, order_service_id ON work_assignments
FOR EACH ROW EXECUTE FUNCTION fn_check_master_qualification();

-- 2.2. Автоматическое завершение услуги и заказа.
CREATE OR REPLACE FUNCTION fn_sync_service_and_order_completion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_order_id INTEGER;
BEGIN
    IF NEW.completed_at IS NOT NULL
       AND OLD.completed_at IS DISTINCT FROM NEW.completed_at THEN

        IF NOT EXISTS (
            SELECT 1
              FROM work_assignments wa
             WHERE wa.order_service_id = NEW.order_service_id
               AND wa.completed_at IS NULL
        ) THEN
            UPDATE order_services
               SET service_status = 'выполнена'
             WHERE order_service_id = NEW.order_service_id;
        END IF;

        SELECT os.order_id
          INTO v_order_id
          FROM order_services os
         WHERE os.order_service_id = NEW.order_service_id;

        IF EXISTS (
            SELECT 1 FROM order_services os WHERE os.order_id = v_order_id
        ) AND NOT EXISTS (
            SELECT 1
              FROM order_services os
             WHERE os.order_id = v_order_id
               AND os.service_status <> 'выполнена'
        ) THEN
            UPDATE orders
               SET actual_end_date = COALESCE(actual_end_date, CURRENT_DATE),
                   status = 'готов'
             WHERE order_id = v_order_id;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_assignment_completion_sync ON work_assignments;
CREATE TRIGGER trg_assignment_completion_sync
AFTER UPDATE OF completed_at ON work_assignments
FOR EACH ROW EXECUTE FUNCTION fn_sync_service_and_order_completion();

-- 2.3. Проверка остатка и списание детали автомастерской.
CREATE OR REPLACE FUNCTION fn_consume_inventory_part()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_workshop_id INTEGER;
    v_stock INTEGER;
BEGIN
    IF NEW.source = 'автомастерская' THEN
        SELECT ct.workshop_id
          INTO v_workshop_id
          FROM order_services os
          JOIN orders o ON o.order_id = os.order_id
          JOIN contracts ct ON ct.contract_id = o.contract_id
         WHERE os.order_service_id = NEW.order_service_id;

        SELECT i.quantity
          INTO v_stock
          FROM inventory i
         WHERE i.workshop_id = v_workshop_id
           AND i.part_id = NEW.part_id
         FOR UPDATE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Деталь % отсутствует на складе мастерской %',
                NEW.part_id, v_workshop_id;
        END IF;
        IF v_stock < NEW.quantity THEN
            RAISE EXCEPTION 'Недостаточный остаток детали %: доступно %, требуется %',
                NEW.part_id, v_stock, NEW.quantity;
        END IF;

        UPDATE inventory
           SET quantity = quantity - NEW.quantity
         WHERE workshop_id = v_workshop_id AND part_id = NEW.part_id;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_used_part_consume_inventory ON used_parts;
CREATE TRIGGER trg_used_part_consume_inventory
BEFORE INSERT ON used_parts
FOR EACH ROW EXECUTE FUNCTION fn_consume_inventory_part();

-- 2.4. Возврат детали на склад при удалении записи об использовании.
CREATE OR REPLACE FUNCTION fn_restore_inventory_part()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_workshop_id INTEGER;
BEGIN
    IF OLD.source = 'автомастерская' THEN
        SELECT ct.workshop_id
          INTO v_workshop_id
          FROM order_services os
          JOIN orders o ON o.order_id = os.order_id
          JOIN contracts ct ON ct.contract_id = o.contract_id
         WHERE os.order_service_id = OLD.order_service_id;

        UPDATE inventory
           SET quantity = quantity + OLD.quantity
         WHERE workshop_id = v_workshop_id AND part_id = OLD.part_id;
    END IF;

    RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_used_part_restore_inventory ON used_parts;
CREATE TRIGGER trg_used_part_restore_inventory
AFTER DELETE ON used_parts
FOR EACH ROW EXECUTE FUNCTION fn_restore_inventory_part();

-- 2.5. Аудит вставки, изменения и удаления стоимости работ.
CREATE OR REPLACE FUNCTION fn_audit_work_price()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO work_price_audit
            (work_price_id, work_type_id, operation,
             new_labor_price, new_valid_from, new_valid_to)
        VALUES
            (NEW.work_price_id, NEW.work_type_id, TG_OP,
             NEW.labor_price, NEW.valid_from, NEW.valid_to);
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO work_price_audit
            (work_price_id, work_type_id, operation,
             old_labor_price, new_labor_price,
             old_valid_from, old_valid_to, new_valid_from, new_valid_to)
        VALUES
            (NEW.work_price_id, NEW.work_type_id, TG_OP,
             OLD.labor_price, NEW.labor_price,
             OLD.valid_from, OLD.valid_to, NEW.valid_from, NEW.valid_to);
        RETURN NEW;
    ELSE
        INSERT INTO work_price_audit
            (work_price_id, work_type_id, operation,
             old_labor_price, old_valid_from, old_valid_to)
        VALUES
            (OLD.work_price_id, OLD.work_type_id, TG_OP,
             OLD.labor_price, OLD.valid_from, OLD.valid_to);
        RETURN OLD;
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_work_price_audit ON work_prices;
CREATE TRIGGER trg_work_price_audit
AFTER INSERT OR UPDATE OR DELETE ON work_prices
FOR EACH ROW EXECUTE FUNCTION fn_audit_work_price();

-- 2.6. Запрет изменения уже выданного заказа.
CREATE OR REPLACE FUNCTION fn_protect_issued_order()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.status = 'выдан' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'Заказ % уже выдан клиенту и не может быть изменён',
            OLD.order_id;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_issued_order ON orders;
CREATE TRIGGER trg_protect_issued_order
BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION fn_protect_issued_order();

-- 2.7. Автоматическое закрытие предыдущего периода цены и защита от пересечений.
CREATE OR REPLACE FUNCTION fn_manage_work_price_period()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE work_prices
       SET valid_to = NEW.valid_from - 1
     WHERE work_type_id = NEW.work_type_id
       AND valid_to IS NULL
       AND valid_from < NEW.valid_from;

    IF EXISTS (
        SELECT 1
          FROM work_prices wp
         WHERE wp.work_type_id = NEW.work_type_id
           AND DATERANGE(
                   wp.valid_from,
                   COALESCE(wp.valid_to, 'infinity'::DATE),
                   '[]'
               ) && DATERANGE(
                   NEW.valid_from,
                   COALESCE(NEW.valid_to, 'infinity'::DATE),
                   '[]'
               )
    ) THEN
        RAISE EXCEPTION 'Период новой цены пересекается с существующим периодом';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_manage_work_price_period ON work_prices;
CREATE TRIGGER trg_manage_work_price_period
BEFORE INSERT ON work_prices
FOR EACH ROW EXECUTE FUNCTION fn_manage_work_price_period();

-- =====================================================================
-- 3. ПРОВЕРКА ПРОЦЕДУР В psql
-- =====================================================================

\echo 'Проверка процедуры 1: цена деталей Ford до и после повышения'
BEGIN;
SELECT p.part_id, p.part_name, p.unit_price
FROM parts p
JOIN part_brand_compatibility pbc ON pbc.part_id = p.part_id
JOIN car_brands b ON b.brand_id = pbc.brand_id
WHERE b.brand_name = 'Ford'
ORDER BY p.part_id;
CALL p_increase_part_prices('Ford', 10, 0);
SELECT p.part_id, p.part_name, p.unit_price
FROM parts p
JOIN part_brand_compatibility pbc ON pbc.part_id = p.part_id
JOIN car_brands b ON b.brand_id = pbc.brand_id
WHERE b.brand_name = 'Ford'
ORDER BY p.part_id;
ROLLBACK;

\echo 'Проверка процедуры 2: разряд мастеров до и после повышения'
BEGIN;
SELECT employee_id, last_name, grade FROM employees
WHERE position_id = (SELECT position_id FROM positions WHERE position_name = 'мастер')
ORDER BY employee_id;
CALL p_promote_productive_masters(3, 0);
SELECT employee_id, last_name, grade FROM employees
WHERE position_id = (SELECT position_id FROM positions WHERE position_name = 'мастер')
ORDER BY employee_id;
ROLLBACK;

\echo 'Проверка процедуры 3: ремонты мастеров за текущий квартал'
BEGIN;
CALL p_repaired_cars_by_master(
    DATE_TRUNC('quarter', CURRENT_DATE)::DATE,
    'quarter_repair_counts'
);
FETCH ALL FROM quarter_repair_counts;
COMMIT;

-- =====================================================================
-- 4. ПРОВЕРКА ТРИГГЕРОВ В psql
-- =====================================================================

\echo 'Триггер 1: мастер без требуемой специализации отклоняется'
DO $$
BEGIN
    BEGIN
        INSERT INTO work_assignments
            (assignment_id, order_service_id, master_id,
             assigned_by_administrator_id, assigned_at, labor_cost)
        VALUES (950001, 3, 2, 1, CURRENT_TIMESTAMP, 4200.00);
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Ожидаемая ошибка: %', SQLERRM;
    END;
END;
$$;

\echo 'Триггер 2: завершение назначения завершает услугу и заказ'
BEGIN;
SELECT o.order_id, o.status, o.actual_end_date, os.service_status
FROM orders o JOIN order_services os ON os.order_id = o.order_id
WHERE o.order_id = 2;
UPDATE work_assignments
SET completed_at = CURRENT_TIMESTAMP
WHERE assignment_id = 3;
SELECT o.order_id, o.status, o.actual_end_date, os.service_status
FROM orders o JOIN order_services os ON os.order_id = o.order_id
WHERE o.order_id = 2;
ROLLBACK;

\echo 'Триггер 3: списание детали со склада'
BEGIN;
SELECT workshop_id, part_id, quantity FROM inventory
WHERE workshop_id = 1 AND part_id = 1;
INSERT INTO used_parts
    (used_part_id, order_service_id, part_id, source, quantity, unit_price)
VALUES
    (950001, 1, 1, 'автомастерская', 1, 950.00);
SELECT workshop_id, part_id, quantity FROM inventory
WHERE workshop_id = 1 AND part_id = 1;
ROLLBACK;

\echo 'Триггер 4: возврат детали на склад при удалении'
BEGIN;
SELECT workshop_id, part_id, quantity FROM inventory
WHERE workshop_id = 1 AND part_id = 1;
DELETE FROM used_parts WHERE used_part_id = 1;
SELECT workshop_id, part_id, quantity FROM inventory
WHERE workshop_id = 1 AND part_id = 1;
ROLLBACK;

\echo 'Триггеры 5 и 7: аудит цены и управление периодами'
BEGIN;
SELECT work_price_id, work_type_id, valid_from, valid_to, labor_price
FROM work_prices WHERE work_type_id = 1 ORDER BY valid_from;
INSERT INTO work_prices
    (work_price_id, work_type_id, valid_from, valid_to, labor_price)
VALUES
    (950001, 1, CURRENT_DATE + 1, NULL, 2750.00);
SELECT work_price_id, work_type_id, valid_from, valid_to, labor_price
FROM work_prices WHERE work_type_id = 1 ORDER BY valid_from;
SELECT operation, work_price_id, old_labor_price, new_labor_price,
       old_valid_to, new_valid_to
FROM work_price_audit
ORDER BY audit_id;
ROLLBACK;

\echo 'Триггер 6: изменение выданного заказа запрещается'
DO $$
BEGIN
    BEGIN
        UPDATE orders
           SET planned_end_date = planned_end_date + 1
         WHERE order_id = 1;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Ожидаемая ошибка: %', SQLERRM;
    END;
END;
$$;

-- =====================================================================
-- 5. ПРОВЕРКА СОЗДАННЫХ ОБЪЕКТОВ В СИСТЕМНОМ КАТАЛОГЕ
-- =====================================================================

SELECT n.nspname AS schema_name,
       p.proname AS routine_name,
       CASE p.prokind WHEN 'p' THEN 'PROCEDURE' ELSE 'FUNCTION' END AS routine_kind
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'autoservice'
  AND (LEFT(p.proname, 2) = 'p_' OR LEFT(p.proname, 3) = 'fn_')
ORDER BY routine_kind, routine_name;

SELECT event_object_table AS table_name,
       trigger_name,
       action_timing,
       event_manipulation
FROM information_schema.triggers
WHERE trigger_schema = 'autoservice'
  AND LEFT(trigger_name, 4) = 'trg_'
ORDER BY trigger_name, event_manipulation;

\echo 'ЛР5 выполнена. Демонстрационные изменения отменены командами ROLLBACK.'

-- Удаление объектов при необходимости:
-- DROP PROCEDURE p_increase_part_prices(TEXT, NUMERIC, INTEGER);
-- DROP PROCEDURE p_promote_productive_masters(INTEGER, INTEGER);
-- DROP PROCEDURE p_repaired_cars_by_master(DATE, REFCURSOR);
-- DROP TABLE work_price_audit;
-- DROP TABLE part_brand_compatibility;
