-- Лабораторная работа 3. Вариант 11. БД «Автомастерская».
CREATE DATABASE autoservice_v11
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    TEMPLATE = template0;

-- Переключение на созданную БД при выполнении файла через psql.
\connect autoservice_v11

BEGIN;

-- Отдельная схема объединяет объекты предметной области.
CREATE SCHEMA IF NOT EXISTS autoservice;
SET search_path TO autoservice, public;

-- Справочник марок автомобилей.
CREATE TABLE car_brands (
    brand_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name      VARCHAR(50) NOT NULL,
    country         VARCHAR(50) NOT NULL,
    CONSTRAINT uq_car_brands_name UNIQUE (brand_name)
);

-- Клиенты автомастерской.
CREATE TABLE clients (
    client_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name       VARCHAR(50) NOT NULL,
    first_name      VARCHAR(50) NOT NULL,
    middle_name     VARCHAR(50),
    phone           VARCHAR(20) NOT NULL,
    email           VARCHAR(100),
    CONSTRAINT uq_clients_phone UNIQUE (phone),
    CONSTRAINT uq_clients_email UNIQUE (email),
    CONSTRAINT ck_clients_phone CHECK (phone ~ '^\+7\([0-9]{3}\)[0-9]{3}-[0-9]{2}-[0-9]{2}$'),
    CONSTRAINT ck_clients_email CHECK (email IS NULL OR email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

-- Паспортные данные.
CREATE TABLE passport_data (
    passport_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       INTEGER NOT NULL,
    series          CHAR(4) NOT NULL,
    number          CHAR(6) NOT NULL,
    issue_date      DATE NOT NULL,
    issued_by       VARCHAR(150) NOT NULL,
    birth_date      DATE NOT NULL,
    birth_place     VARCHAR(100),
    registration_address VARCHAR(200),
    CONSTRAINT fk_passport_client FOREIGN KEY (client_id)
        REFERENCES clients (client_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_passport_client UNIQUE (client_id),
    CONSTRAINT uq_passport_number UNIQUE (series, number),
    CONSTRAINT ck_passport_series CHECK (series ~ '^[0-9]{4}$'),
    CONSTRAINT ck_passport_number CHECK (number ~ '^[0-9]{6}$'),
    CONSTRAINT ck_passport_issue_date CHECK (issue_date <= CURRENT_DATE),
    CONSTRAINT ck_passport_birth_date CHECK (birth_date >= DATE '1900-01-01' AND birth_date < issue_date)
);

-- Водительские удостоверения клиентов.
CREATE TABLE driver_licenses (
    license_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       INTEGER NOT NULL,
    series          CHAR(4) NOT NULL,
    number          CHAR(6) NOT NULL,
    issue_date      DATE NOT NULL,
    expiry_date     DATE NOT NULL,
    category        VARCHAR(5) NOT NULL,
    subcategory     VARCHAR(5),
    issuing_unit    VARCHAR(100),
    CONSTRAINT fk_license_client FOREIGN KEY (client_id)
        REFERENCES clients (client_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_license_client UNIQUE (client_id),
    CONSTRAINT uq_license_number UNIQUE (series, number),
    CONSTRAINT ck_license_series CHECK (series ~ '^[0-9]{4}$'),
    CONSTRAINT ck_license_number CHECK (number ~ '^[0-9]{6}$'),
    CONSTRAINT ck_license_issue_date CHECK (issue_date <= CURRENT_DATE),
    CONSTRAINT ck_license_expiry CHECK (expiry_date > issue_date),
    CONSTRAINT ck_license_category CHECK (category IN ('A', 'B', 'C', 'D', 'BE')),
    CONSTRAINT ck_license_subcategory CHECK (subcategory IS NULL OR subcategory IN ('A1', 'B1', 'C1'))
);

-- Автомобили принадлежат клиентам.
CREATE TABLE cars (
    car_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        INTEGER NOT NULL,
    brand_id        INTEGER NOT NULL,
    model_name      VARCHAR(50) NOT NULL,
    registration_number VARCHAR(12) NOT NULL,
    vehicle_type    VARCHAR(20) NOT NULL,
    production_year SMALLINT NOT NULL,
    power_hp        SMALLINT NOT NULL,
    body_color      VARCHAR(20),
    interior_color  VARCHAR(20),
    steering_position VARCHAR(10) NOT NULL,
    drive_type      VARCHAR(15) NOT NULL,
    seat_count      SMALLINT NOT NULL,
    vehicle_class   VARCHAR(20),
    configuration   VARCHAR(100),
    CONSTRAINT fk_cars_owner FOREIGN KEY (owner_id)
        REFERENCES clients (client_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_cars_brand FOREIGN KEY (brand_id)
        REFERENCES car_brands (brand_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_cars_registration UNIQUE (registration_number),
    CONSTRAINT ck_cars_registration CHECK (registration_number ~ '^[АВЕКМНОРСТУХABEKMHOPCTYX][0-9]{3}[АВЕКМНОРСТУХABEKMHOPCTYX]{2}[0-9]{2,3}$'),
    CONSTRAINT ck_cars_vehicle_type CHECK (vehicle_type IN ('легковой', 'внедорожник', 'микроавтобус', 'грузовой')),
    CONSTRAINT ck_cars_year CHECK (production_year BETWEEN 1950 AND EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER),
    CONSTRAINT ck_cars_power CHECK (power_hp > 0),
    CONSTRAINT ck_cars_steering CHECK (steering_position IN ('левый', 'правый')),
    CONSTRAINT ck_cars_drive CHECK (drive_type IN ('передний', 'задний', 'полный')),
    CONSTRAINT ck_cars_seats CHECK (seat_count BETWEEN 1 AND 8)
);

-- Автомастерские сети.
CREATE TABLE workshops (
    workshop_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workshop_name   VARCHAR(100) NOT NULL,
    address         VARCHAR(200) NOT NULL,
    phone           VARCHAR(20) NOT NULL,
    CONSTRAINT uq_workshops_name UNIQUE (workshop_name),
    CONSTRAINT uq_workshops_address UNIQUE (address),
    CONSTRAINT ck_workshops_phone CHECK (phone ~ '^\+7\([0-9]{3}\)[0-9]{3}-[0-9]{2}-[0-9]{2}$')
);

-- Должности и штатные ставки вынесены в справочник.
CREATE TABLE positions (
    position_id     SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_name   VARCHAR(30) NOT NULL,
    default_rate    NUMERIC(3,2) NOT NULL DEFAULT 1.00,
    CONSTRAINT uq_positions_name UNIQUE (position_name),
    CONSTRAINT ck_positions_rate CHECK (default_rate BETWEEN 0.25 AND 2.00)
);

-- Специализации мастеров.
CREATE TABLE specializations (
    specialization_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialization_name VARCHAR(80) NOT NULL,
    CONSTRAINT uq_specializations_name UNIQUE (specialization_name)
);

-- Сотрудники сети автомастерских.
CREATE TABLE employees (
    employee_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workshop_id     INTEGER NOT NULL,
    position_id     SMALLINT NOT NULL,
    last_name       VARCHAR(50) NOT NULL,
    first_name      VARCHAR(50) NOT NULL,
    middle_name     VARCHAR(50),
    grade           SMALLINT,
    employment_rate NUMERIC(3,2) NOT NULL DEFAULT 1.00,
    experience_years SMALLINT NOT NULL DEFAULT 0,
    phone           VARCHAR(20),
    CONSTRAINT fk_employees_workshop FOREIGN KEY (workshop_id)
        REFERENCES workshops (workshop_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_employees_position FOREIGN KEY (position_id)
        REFERENCES positions (position_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_employees_phone UNIQUE (phone),
    CONSTRAINT ck_employees_grade CHECK (grade IS NULL OR grade BETWEEN 1 AND 6),
    CONSTRAINT ck_employees_rate CHECK (employment_rate BETWEEN 0.25 AND 2.00),
    CONSTRAINT ck_employees_experience CHECK (experience_years >= 0),
    CONSTRAINT ck_employees_phone CHECK (phone IS NULL OR phone ~ '^\+7\([0-9]{3}\)[0-9]{3}-[0-9]{2}-[0-9]{2}$')
);

-- Связь многие-ко-многим между сотрудниками и специализациями.
-- Составной естественный ключ заменён суррогатным employee_specialization_id.
CREATE TABLE employee_specializations (
    employee_specialization_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     INTEGER NOT NULL,
    specialization_id SMALLINT NOT NULL,
    CONSTRAINT fk_employee_spec_employee FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_employee_spec_specialization FOREIGN KEY (specialization_id)
        REFERENCES specializations (specialization_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_employee_specialization UNIQUE (employee_id, specialization_id)
);

-- Виды ремонтных и профилактических работ.
CREATE TABLE work_types (
    work_type_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_type_name  VARCHAR(100) NOT NULL,
    description     TEXT,
    CONSTRAINT uq_work_types_name UNIQUE (work_type_name)
);

-- Требуемые специализации для видов работ.
CREATE TABLE work_type_specializations (
    work_type_specialization_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_type_id    INTEGER NOT NULL,
    specialization_id SMALLINT NOT NULL,
    CONSTRAINT fk_work_type_spec_work FOREIGN KEY (work_type_id)
        REFERENCES work_types (work_type_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_work_type_spec_specialization FOREIGN KEY (specialization_id)
        REFERENCES specializations (specialization_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_work_type_specialization UNIQUE (work_type_id, specialization_id)
);

-- История изменения стоимости работ.
CREATE TABLE work_prices (
    work_price_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_type_id    INTEGER NOT NULL,
    valid_from      DATE NOT NULL,
    valid_to        DATE,
    labor_price     NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_work_prices_type FOREIGN KEY (work_type_id)
        REFERENCES work_types (work_type_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_work_prices_period UNIQUE (work_type_id, valid_from),
    CONSTRAINT ck_work_prices_value CHECK (labor_price > 0),
    CONSTRAINT ck_work_prices_period CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- Договор с клиентом сопровождает администратор выбранной мастерской.
CREATE TABLE contracts (
    contract_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_number VARCHAR(20) NOT NULL,
    client_id       INTEGER NOT NULL,
    workshop_id     INTEGER NOT NULL,
    administrator_id INTEGER NOT NULL,
    contract_date   DATE NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'заключён',
    CONSTRAINT fk_contracts_client FOREIGN KEY (client_id)
        REFERENCES clients (client_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_contracts_workshop FOREIGN KEY (workshop_id)
        REFERENCES workshops (workshop_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_contracts_administrator FOREIGN KEY (administrator_id)
        REFERENCES employees (employee_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_contracts_number UNIQUE (contract_number),
    CONSTRAINT ck_contracts_date CHECK (contract_date <= CURRENT_DATE),
    CONSTRAINT ck_contracts_status CHECK (status IN ('заключён', 'в работе', 'выполнен', 'расторгнут'))
);

-- Заказ на ремонт конкретного автомобиля в рамках договора.
CREATE TABLE orders (
    order_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id     INTEGER NOT NULL,
    car_id          INTEGER NOT NULL,
    accepted_date   DATE NOT NULL,
    planned_end_date DATE NOT NULL,
    actual_end_date DATE,
    order_description TEXT,
    reported_faults TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'принят',
    CONSTRAINT fk_orders_contract FOREIGN KEY (contract_id)
        REFERENCES contracts (contract_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_orders_car FOREIGN KEY (car_id)
        REFERENCES cars (car_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_orders_accepted CHECK (accepted_date <= CURRENT_DATE),
    CONSTRAINT ck_orders_planned_end CHECK (planned_end_date >= accepted_date),
    CONSTRAINT ck_orders_actual_end CHECK (actual_end_date IS NULL OR actual_end_date >= accepted_date),
    CONSTRAINT ck_orders_status CHECK (status IN ('принят', 'диагностика', 'ремонт', 'готов', 'выдан'))
);

-- Услуги, включённые в заказ. Цена фиксируется на дату заказа.
CREATE TABLE order_services (
    order_service_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        INTEGER NOT NULL,
    work_type_id    INTEGER NOT NULL,
    quantity        SMALLINT NOT NULL DEFAULT 1,
    labor_price     NUMERIC(12,2) NOT NULL,
    service_status  VARCHAR(20) NOT NULL DEFAULT 'запланирована',
    CONSTRAINT fk_order_services_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_order_services_type FOREIGN KEY (work_type_id)
        REFERENCES work_types (work_type_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_order_service UNIQUE (order_id, work_type_id),
    CONSTRAINT ck_order_services_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_services_price CHECK (labor_price > 0),
    CONSTRAINT ck_order_services_status CHECK (service_status IN ('запланирована', 'выполняется', 'выполнена', 'отменена'))
);

-- Назначение мастеров на услуги выполняет администратор.
CREATE TABLE work_assignments (
    assignment_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_service_id INTEGER NOT NULL,
    master_id       INTEGER NOT NULL,
    assigned_by_administrator_id INTEGER NOT NULL,
    assigned_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMP,
    labor_cost      NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_assignments_service FOREIGN KEY (order_service_id)
        REFERENCES order_services (order_service_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_assignments_master FOREIGN KEY (master_id)
        REFERENCES employees (employee_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_assignments_admin FOREIGN KEY (assigned_by_administrator_id)
        REFERENCES employees (employee_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_assignment_master UNIQUE (order_service_id, master_id),
    CONSTRAINT ck_assignments_completed CHECK (completed_at IS NULL OR completed_at >= assigned_at),
    CONSTRAINT ck_assignments_cost CHECK (labor_cost > 0)
);

-- Справочник деталей и расходных материалов.
CREATE TABLE parts (
    part_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number   VARCHAR(50),
    part_name       VARCHAR(100) NOT NULL,
    unit_price      NUMERIC(12,2) NOT NULL,
    material        VARCHAR(50),
    color           VARCHAR(20),
    manufacturer_country VARCHAR(50),
    CONSTRAINT uq_parts_serial UNIQUE (serial_number),
    CONSTRAINT ck_parts_price CHECK (unit_price > 0)
);

-- Остатки деталей по мастерским.
-- Составной ключ из ЛР №2 заменён суррогатным inventory_id.
CREATE TABLE inventory (
    inventory_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workshop_id     INTEGER NOT NULL,
    part_id         INTEGER NOT NULL,
    quantity        INTEGER NOT NULL DEFAULT 0,
    minimum_stock   INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_inventory_workshop FOREIGN KEY (workshop_id)
        REFERENCES workshops (workshop_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_inventory_part FOREIGN KEY (part_id)
        REFERENCES parts (part_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_inventory_item UNIQUE (workshop_id, part_id),
    CONSTRAINT ck_inventory_quantity CHECK (quantity >= 0),
    CONSTRAINT ck_inventory_minimum CHECK (minimum_stock >= 0)
);

-- Детали, использованные при выполнении услуги.
-- Цена фиксируется, а источник определяет включение детали в смету.
CREATE TABLE used_parts (
    used_part_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_service_id INTEGER NOT NULL,
    part_id         INTEGER NOT NULL,
    source          VARCHAR(20) NOT NULL,
    quantity        SMALLINT NOT NULL,
    unit_price      NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_used_parts_service FOREIGN KEY (order_service_id)
        REFERENCES order_services (order_service_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_used_parts_part FOREIGN KEY (part_id)
        REFERENCES parts (part_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_used_parts_source CHECK (source IN ('автомастерская', 'клиент')),
    CONSTRAINT ck_used_parts_quantity CHECK (quantity > 0),
    CONSTRAINT ck_used_parts_price CHECK (unit_price >= 0),
    CONSTRAINT ck_used_parts_client_price CHECK (source <> 'клиент' OR unit_price = 0)
);

-- Проверка ролей сотрудников и принадлежности администратора мастерской.
CREATE OR REPLACE FUNCTION check_employee_roles()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    master_position VARCHAR(30);
    admin_position VARCHAR(30);
    admin_workshop INTEGER;
BEGIN
    IF TG_TABLE_NAME = 'contracts' THEN
        SELECT p.position_name, e.workshop_id
          INTO admin_position, admin_workshop
          FROM employees e
          JOIN positions p ON p.position_id = e.position_id
         WHERE e.employee_id = NEW.administrator_id;

        IF admin_position IS DISTINCT FROM 'администратор' OR admin_workshop <> NEW.workshop_id THEN
            RAISE EXCEPTION 'Договор должен сопровождать администратор выбранной мастерской';
        END IF;
    ELSIF TG_TABLE_NAME = 'work_assignments' THEN
        SELECT p.position_name
          INTO master_position
          FROM employees e
          JOIN positions p ON p.position_id = e.position_id
         WHERE e.employee_id = NEW.master_id;

        SELECT p.position_name
          INTO admin_position
          FROM employees e
          JOIN positions p ON p.position_id = e.position_id
         WHERE e.employee_id = NEW.assigned_by_administrator_id;

        IF master_position IS DISTINCT FROM 'мастер' THEN
            RAISE EXCEPTION 'На работу может быть назначен только сотрудник с должностью мастер';
        END IF;
        IF admin_position IS DISTINCT FROM 'администратор' THEN
            RAISE EXCEPTION 'Назначение должен выполнить администратор';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_contract_employee_roles
BEFORE INSERT OR UPDATE ON contracts
FOR EACH ROW EXECUTE FUNCTION check_employee_roles();

CREATE TRIGGER trg_assignment_employee_roles
BEFORE INSERT OR UPDATE ON work_assignments
FOR EACH ROW EXECUTE FUNCTION check_employee_roles();

-- Проверка, что автомобиль заказа принадлежит клиенту договора.
CREATE OR REPLACE FUNCTION check_order_car_owner()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    contract_client INTEGER;
    car_owner INTEGER;
BEGIN
    SELECT client_id INTO contract_client FROM contracts WHERE contract_id = NEW.contract_id;
    SELECT owner_id INTO car_owner FROM cars WHERE car_id = NEW.car_id;
    IF contract_client IS DISTINCT FROM car_owner THEN
        RAISE EXCEPTION 'Автомобиль заказа должен принадлежать клиенту договора';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_order_car_owner
BEFORE INSERT OR UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION check_order_car_owner();

-- Представление сметы: детали клиента в стоимость не включаются.
CREATE VIEW order_estimates AS
WITH labor AS (
    SELECT order_id, SUM(labor_price * quantity) AS labor_total
    FROM order_services
    GROUP BY order_id
), workshop_parts AS (
    SELECT os.order_id, SUM(up.unit_price * up.quantity) AS parts_total
    FROM order_services os
    JOIN used_parts up ON up.order_service_id = os.order_service_id
    WHERE up.source = 'автомастерская'
    GROUP BY os.order_id
)
SELECT
    o.order_id,
    c.contract_number,
    ROUND(l.labor_total, 2) AS labor_total,
    ROUND(COALESCE(wp.parts_total, 0), 2) AS workshop_parts_total,
    ROUND(l.labor_total + COALESCE(wp.parts_total, 0), 2) AS estimate_total
FROM orders o
JOIN contracts c ON c.contract_id = o.contract_id
JOIN labor l ON l.order_id = o.order_id
LEFT JOIN workshop_parts wp ON wp.order_id = o.order_id;

-- Представление начисления мастерам: 50% стоимости выполненной ими работы.
CREATE VIEW master_payments AS
SELECT
    wa.assignment_id,
    wa.master_id,
    CONCAT(e.last_name, ' ', e.first_name, ' ', COALESCE(e.middle_name, '')) AS master_name,
    wa.labor_cost,
    ROUND(wa.labor_cost * 0.50, 2) AS master_payment
FROM work_assignments wa
JOIN employees e ON e.employee_id = wa.master_id;

-- Рабочие данные справочников.
INSERT INTO car_brands (brand_id, brand_name, country) VALUES
    (1, 'Toyota', 'Япония'),
    (2, 'Volkswagen', 'Германия'),
    (3, 'LADA', 'Россия');

INSERT INTO clients (client_id, last_name, first_name, middle_name, phone, email) VALUES
    (1, 'Смирнов', 'Алексей', 'Игоревич', '+7(921)555-12-34', 'a.smirnov@example.ru'),
    (2, 'Петрова', 'Марина', 'Олеговна', '+7(911)222-45-67', 'm.petrova@example.ru'),
    (3, 'Ильин', 'Денис', 'Сергеевич', '+7(981)707-18-90', 'd.ilyin@example.ru');

INSERT INTO passport_data
    (client_id, series, number, issue_date, issued_by, birth_date, birth_place, registration_address)
VALUES
    (1, '4015', '123456', DATE '2016-04-12', 'ГУ МВД России по г. Санкт-Петербургу', DATE '1988-02-14', 'г. Санкт-Петербург', 'г. Санкт-Петербург, пр. Науки, д. 10'),
    (2, '4018', '654321', DATE '2019-08-21', 'ГУ МВД России по Ленинградской области', DATE '1992-07-03', 'г. Выборг', 'г. Санкт-Петербург, ул. Бухарестская, д. 18'),
    (3, '4020', '778899', DATE '2021-11-05', 'ГУ МВД России по г. Санкт-Петербургу', DATE '1996-11-20', 'г. Псков', 'г. Санкт-Петербург, ул. Савушкина, д. 44');

INSERT INTO driver_licenses
    (client_id, series, number, issue_date, expiry_date, category, subcategory, issuing_unit)
VALUES
    (1, '7812', '445566', DATE '2018-03-15', DATE '2028-03-15', 'B', 'B1', 'ГИБДД 7801'),
    (2, '7815', '112233', DATE '2020-06-10', DATE '2030-06-10', 'B', NULL, 'ГИБДД 7802'),
    (3, '7818', '987654', DATE '2022-09-01', DATE '2032-09-01', 'B', 'B1', 'ГИБДД 7803');

INSERT INTO cars
    (car_id, owner_id, brand_id, model_name, registration_number, vehicle_type, production_year,
     power_hp, body_color, interior_color, steering_position, drive_type, seat_count,
     vehicle_class, configuration)
VALUES
    (1, 1, 1, 'Camry', 'А123ВС178', 'легковой', 2018, 181, 'чёрный', 'бежевый', 'левый', 'передний', 5, 'E', '2.5 Prestige'),
    (2, 2, 2, 'Tiguan', 'М456ОР98', 'внедорожник', 2020, 150, 'белый', 'чёрный', 'левый', 'полный', 5, 'C-SUV', '2.0 TSI 4Motion'),
    (3, 3, 3, 'Vesta', 'К789ТХ47', 'легковой', 2021, 106, 'серебристый', 'чёрный', 'левый', 'передний', 5, 'B', 'Comfort');

INSERT INTO workshops (workshop_id, workshop_name, address, phone) VALUES
    (1, 'АвтоМастер Север', 'г. Санкт-Петербург, пр. Просвещения, д. 72', '+7(812)600-10-01'),
    (2, 'АвтоМастер Юг', 'г. Санкт-Петербург, Московское ш., д. 25', '+7(812)600-10-02');

INSERT INTO positions (position_id, position_name, default_rate) VALUES
    (1, 'администратор', 1.00),
    (2, 'мастер', 1.00);

INSERT INTO specializations (specialization_id, specialization_name) VALUES
    (1, 'диагностика двигателя'),
    (2, 'ходовая часть'),
    (3, 'тормозные системы'),
    (4, 'техническое обслуживание');

INSERT INTO employees
    (employee_id, workshop_id, position_id, last_name, first_name, middle_name,
     grade, employment_rate, experience_years, phone)
VALUES
    (1, 1, 1, 'Орлова', 'Наталья', 'Викторовна', NULL, 1.00, 6, '+7(921)100-20-30'),
    (2, 1, 2, 'Кузнецов', 'Иван', 'Петрович', 5, 1.00, 9, '+7(921)100-20-31'),
    (3, 1, 2, 'Волков', 'Роман', 'Андреевич', 4, 1.00, 5, '+7(921)100-20-32'),
    (4, 2, 1, 'Захарова', 'Елена', 'Ильинична', NULL, 1.00, 4, '+7(921)100-20-33'),
    (5, 2, 2, 'Морозов', 'Павел', 'Олегович', 6, 1.50, 12, '+7(921)100-20-34');

INSERT INTO employee_specializations (employee_id, specialization_id) VALUES
    (2, 1), (2, 4), (3, 2), (3, 3), (5, 1), (5, 2), (5, 3), (5, 4);

INSERT INTO work_types (work_type_id, work_type_name, description) VALUES
    (1, 'Компьютерная диагностика двигателя', 'Считывание ошибок и проверка параметров двигателя'),
    (2, 'Замена передних тормозных колодок', 'Демонтаж и установка комплекта передних колодок'),
    (3, 'Замена моторного масла', 'Замена масла и масляного фильтра'),
    (4, 'Диагностика подвески', 'Проверка элементов передней и задней подвески');

INSERT INTO work_type_specializations (work_type_id, specialization_id) VALUES
    (1, 1), (2, 3), (3, 4), (4, 2);

INSERT INTO work_prices (work_type_id, valid_from, valid_to, labor_price) VALUES
    (1, DATE '2026-01-01', NULL, 2500.00),
    (2, DATE '2026-01-01', NULL, 4200.00),
    (3, DATE '2026-01-01', NULL, 1800.00),
    (4, DATE '2026-01-01', NULL, 2200.00);

INSERT INTO contracts
    (contract_id, contract_number, client_id, workshop_id, administrator_id, contract_date, status)
VALUES
    (1, 'АМ-2026-001', 1, 1, 1, DATE '2026-09-01', 'выполнен'),
    (2, 'АМ-2026-002', 2, 1, 1, DATE '2026-09-08', 'в работе'),
    (3, 'АМ-2026-003', 3, 2, 4, DATE '2026-09-12', 'в работе');

INSERT INTO orders
    (order_id, contract_id, car_id, accepted_date, planned_end_date, actual_end_date,
     order_description, reported_faults, status)
VALUES
    (1, 1, 1, DATE '2026-09-01', DATE '2026-09-02', DATE '2026-09-02', 'Диагностика и плановое ТО', 'Загорелся индикатор Check Engine', 'выдан'),
    (2, 2, 2, DATE '2026-09-08', DATE '2026-09-10', NULL, 'Обслуживание тормозной системы', 'Скрип при торможении', 'ремонт'),
    (3, 3, 3, DATE '2026-09-12', DATE '2026-09-14', NULL, 'Проверка подвески', 'Стук при проезде неровностей', 'диагностика');

INSERT INTO order_services
    (order_service_id, order_id, work_type_id, quantity, labor_price, service_status)
VALUES
    (1, 1, 1, 1, 2500.00, 'выполнена'),
    (2, 1, 3, 1, 1800.00, 'выполнена'),
    (3, 2, 2, 1, 4200.00, 'выполняется'),
    (4, 3, 4, 1, 2200.00, 'запланирована');

INSERT INTO work_assignments
    (assignment_id, order_service_id, master_id, assigned_by_administrator_id,
     assigned_at, completed_at, labor_cost)
VALUES
    (1, 1, 2, 1, TIMESTAMP '2026-09-01 10:00:00', TIMESTAMP '2026-09-01 12:00:00', 2500.00),
    (2, 2, 2, 1, TIMESTAMP '2026-09-01 12:30:00', TIMESTAMP '2026-09-01 14:00:00', 1800.00),
    (3, 3, 3, 1, TIMESTAMP '2026-09-08 11:00:00', NULL, 4200.00),
    (4, 4, 5, 4, TIMESTAMP '2026-09-12 15:00:00', NULL, 2200.00);

INSERT INTO parts
    (part_id, serial_number, part_name, unit_price, material, color, manufacturer_country)
VALUES
    (1, 'OF-TY-04152', 'Масляный фильтр', 950.00, 'металл/бумага', NULL, 'Япония'),
    (2, 'OIL-5W30-4L', 'Моторное масло 5W-30, 4 л', 4800.00, 'синтетическое масло', 'янтарный', 'Финляндия'),
    (3, 'BP-VW-FRONT', 'Комплект передних тормозных колодок', 6900.00, 'композит', 'чёрный', 'Германия'),
    (4, NULL, 'Втулка стабилизатора', 1200.00, 'резина/металл', 'чёрный', 'Россия');

INSERT INTO inventory (workshop_id, part_id, quantity, minimum_stock) VALUES
    (1, 1, 12, 4),
    (1, 2, 8, 3),
    (1, 3, 5, 2),
    (2, 1, 7, 3),
    (2, 4, 10, 4);

INSERT INTO used_parts
    (used_part_id, order_service_id, part_id, source, quantity, unit_price)
VALUES
    (1, 2, 1, 'автомастерская', 1, 950.00),
    (2, 2, 2, 'автомастерская', 1, 4800.00),
    (3, 3, 3, 'клиент', 1, 0.00);

-- Синхронизация последовательностей после вставки демонстрационных идентификаторов.
SELECT setval(pg_get_serial_sequence('car_brands', 'brand_id'), (SELECT MAX(brand_id) FROM car_brands));
SELECT setval(pg_get_serial_sequence('clients', 'client_id'), (SELECT MAX(client_id) FROM clients));
SELECT setval(pg_get_serial_sequence('cars', 'car_id'), (SELECT MAX(car_id) FROM cars));
SELECT setval(pg_get_serial_sequence('workshops', 'workshop_id'), (SELECT MAX(workshop_id) FROM workshops));
SELECT setval(pg_get_serial_sequence('positions', 'position_id'), (SELECT MAX(position_id) FROM positions));
SELECT setval(pg_get_serial_sequence('specializations', 'specialization_id'), (SELECT MAX(specialization_id) FROM specializations));
SELECT setval(pg_get_serial_sequence('employees', 'employee_id'), (SELECT MAX(employee_id) FROM employees));
SELECT setval(pg_get_serial_sequence('work_types', 'work_type_id'), (SELECT MAX(work_type_id) FROM work_types));
SELECT setval(pg_get_serial_sequence('contracts', 'contract_id'), (SELECT MAX(contract_id) FROM contracts));
SELECT setval(pg_get_serial_sequence('orders', 'order_id'), (SELECT MAX(order_id) FROM orders));
SELECT setval(pg_get_serial_sequence('order_services', 'order_service_id'), (SELECT MAX(order_service_id) FROM order_services));
SELECT setval(pg_get_serial_sequence('work_assignments', 'assignment_id'), (SELECT MAX(assignment_id) FROM work_assignments));
SELECT setval(pg_get_serial_sequence('parts', 'part_id'), (SELECT MAX(part_id) FROM parts));
SELECT setval(pg_get_serial_sequence('used_parts', 'used_part_id'), (SELECT MAX(used_part_id) FROM used_parts));

COMMIT;

-- Проверка содержимого таблиц и расчётных представлений.
SET search_path TO autoservice, public;
SELECT * FROM clients ORDER BY client_id;
SELECT * FROM cars ORDER BY car_id;
SELECT * FROM contracts ORDER BY contract_id;
SELECT * FROM orders ORDER BY order_id;
SELECT * FROM order_services ORDER BY order_service_id;
SELECT * FROM order_estimates ORDER BY order_id;
SELECT * FROM master_payments ORDER BY assignment_id;
